Emotion6_classes = [
    "anger",
    "disgust",
    "fear",
    "joy",
    "sadness",
    "surprise"
]

ds_specific_templates = {
    # Comprehensive Emotion6 Templates - 100+ diverse templates covering all visual representations
    'Emotion6': [
    # Basic emotional representation templates
    'a photo representing {}.',
    'an image that evokes {}.',
    'a picture that conveys {}.',
    'a visual representation of {}.',
    'a scene depicting {}.',
    'an image associated with {}.',
    'a photograph that expresses {}.',
    'a picture that symbolizes {}.',
    'content that represents the emotion of {}.',
    'a visual that embodies {}.',
    
    # Human expression and portrait templates
    'a photo of a {} face.',
    'a photo of a person showing {}.',
    'a photo of a {} expression.',
    'a picture of someone feeling {}.',
    'a facial expression of {}.',
    'a person expressing {}.',
    'a {} facial expression.',
    'someone displaying {}.',
    'a face showing {}.',
    'a portrait of {} emotion.',
    'a child expressing {}.',
    'an adult showing {}.',
    'people experiencing {}.',
    'a human moment of {}.',
    'eyes that reflect {}.',
    
    # Nature and landscape templates
    'a landscape that evokes {}.',
    'nature representing {}.',
    'a natural scene of {}.',
    'weather that suggests {}.',
    'a sky that conveys {}.',
    'clouds that express {}.',
    'a sunset that embodies {}.',
    'water that reflects {}.',
    'mountains that inspire {}.',
    'a forest scene of {}.',
    'natural elements suggesting {}.',
    'outdoor scenery evoking {}.',
    'a beach scene representing {}.',
    'wilderness that conveys {}.',
    'seasonal imagery of {}.',
    
    # Animal and creature templates
    'an animal showing {}.',
    'a creature expressing {}.',
    'wildlife that represents {}.',
    'a pet displaying {}.',
    'an animal in a {} state.',
    'birds that symbolize {}.',
    'marine life suggesting {}.',
    'domestic animals expressing {}.',
    'wild animals embodying {}.',
    'creatures in {} situations.',
    
    # Object and symbolic templates
    'an object that represents {}.',
    'something that symbolizes {}.',
    'an item associated with {}.',
    'a thing that causes {}.',
    'something that triggers {}.',
    'an element that conveys {}.',
    'a symbol of {}.',
    'something representing the feeling of {}.',
    'an object that evokes {}.',
    'something that embodies {}.',
    'colors that suggest {}.',
    'textures that evoke {}.',
    'patterns representing {}.',
    'shapes that convey {}.',
    'materials that express {}.',
    
    # Architecture and environment templates
    'buildings that evoke {}.',
    'architecture representing {}.',
    'urban scenes of {}.',
    'interior spaces suggesting {}.',
    'rooms that convey {}.',
    'structures that embody {}.',
    'cityscapes of {}.',
    'abandoned places representing {}.',
    'modern spaces evoking {}.',
    'historical settings of {}.',
    'public spaces that suggest {}.',
    'private spaces expressing {}.',
    
    # Food and consumables templates
    'food that represents {}.',
    'a meal suggesting {}.',
    'cuisine that evokes {}.',
    'drinks that symbolize {}.',
    'cooking that expresses {}.',
    'ingredients representing {}.',
    'dining scenes of {}.',
    'culinary moments of {}.',
    
    # Artistic and creative templates
    'art that expresses {}.',
    'a painting of {}.',
    'sculpture representing {}.',
    'creative work showing {}.',
    'artistic expression of {}.',
    'crafts that embody {}.',
    'design elements suggesting {}.',
    'visual art conveying {}.',
    'handmade items of {}.',
    'artistic interpretation of {}.',
    
    # Activity and action templates
    'activities that bring {}.',
    'actions that cause {}.',
    'movement expressing {}.',
    'sports that evoke {}.',
    'games representing {}.',
    'work that suggests {}.',
    'recreation that embodies {}.',
    'hobbies that convey {}.',
    'exercise expressing {}.',
    'play that represents {}.',
    
    # Abstract and conceptual templates
    'the concept of {}.',
    'the essence of {}.',
    'the embodiment of {}.',
    'the manifestation of {}.',
    'the representation of {}.',
    'the visualization of {}.',
    'the expression of {}.',
    'the display of {}.',
    'the demonstration of {}.',
    'the illustration of {}.',
    'abstract imagery of {}.',
    'conceptual art representing {}.',
    'symbolic representation of {}.',
    'metaphorical imagery of {}.',
    'allegorical scenes of {}.',
    
    # Contextual and atmospheric templates
    'an atmosphere of {}.',
    'a mood of {}.',
    'an ambiance suggesting {}.',
    'lighting that evokes {}.',
    'shadows that represent {}.',
    'brightness that conveys {}.',
    'darkness expressing {}.',
    'contrasts that embody {}.',
    'tones that suggest {}.',
    'hues representing {}.',
    
    # Temporal and situational templates
    'a moment of {}.',
    'an instant of {}.',
    'a memory of {}.',
    'a dream about {}.',
    'a nightmare of {}.',
    'anticipation of {}.',
    'preparation for {}.',
    'aftermath of {}.',
    'during times of {}.',
    'in seasons of {}.',
    
    # Sensory and experiential templates
    'something that feels {}.',
    'textures that seem {}.',
    'sounds that suggest {}.',
    'silence that represents {}.',
    'chaos that embodies {}.',
    'order that expresses {}.',
    'confusion representing {}.',
    'clarity that conveys {}.',
    'complexity suggesting {}.',
    'simplicity embodying {}.'
    ],
        # Comprehensive Abstract Art Templates - 120+ diverse templates covering all visual and emotional aspects
    'Abstract': [
    # Basic abstract art representation templates
    'an abstract artwork that evokes {}.',
    'an abstract painting representing {}.',
    'an abstract image that conveys {}.',
    'abstract art that embodies {}.',
    'a non-representational artwork expressing {}.',
    'an abstract composition that suggests {}.',
    'abstract visual elements that evoke {}.',
    'a painting that abstractly represents {}.',
    'abstract imagery that embodies the feeling of {}.',
    'non-figurative art that expresses {}.',
    
    # Color and composition templates specific to abstract art
    'abstract colors that evoke {}.',
    'color combinations in abstract art representing {}.',
    'abstract color fields expressing {}.',
    'chromatic abstractions that convey {}.',
    'color relationships that suggest {}.',
    'abstract color harmony embodying {}.',
    'pigments arranged to express {}.',
    'abstract color contrasts evoking {}.',
    'hues and tones that represent {}.',
    'abstract color interactions suggesting {}.',
    
    # Form and shape templates for abstract art
    'abstract forms that convey {}.',
    'geometric shapes expressing {}.',
    'organic forms in abstract art representing {}.',
    'abstract shapes that embody {}.',
    'non-representational forms evoking {}.',
    'abstract geometries that suggest {}.',
    'flowing forms that express {}.',
    'angular abstractions conveying {}.',
    'curvilinear elements representing {}.',
    'abstract structural forms embodying {}.',
    
    # Texture and surface quality templates
    'abstract textures that evoke {}.',
    'surface qualities in abstract art expressing {}.',
    'textural elements that convey {}.',
    'abstract surface treatments representing {}.',
    'tactile qualities in abstraction suggesting {}.',
    'material textures that embody {}.',
    'abstract surface variations evoking {}.',
    'layered textures expressing {}.',
    'smooth abstractions that convey {}.',
    'rough textural abstractions representing {}.',
    
    # Movement and rhythm templates
    'abstract movement expressing {}.',
    'rhythmic patterns in abstract art evoking {}.',
    'dynamic abstractions that convey {}.',
    'flowing movements in abstract art representing {}.',
    'static compositions that embody {}.',
    'energetic abstract elements suggesting {}.',
    'calm abstract rhythms expressing {}.',
    'turbulent abstract movement evoking {}.',
    'gentle abstract flows that convey {}.',
    'aggressive abstract dynamics representing {}.',
    
    # Scale and proportion templates
    'large-scale abstractions that evoke {}.',
    'intimate abstract works expressing {}.',
    'monumental abstract art conveying {}.',
    'small abstract details representing {}.',
    'expansive abstract compositions embodying {}.',
    'compressed abstract elements suggesting {}.',
    'overwhelming abstract scale evoking {}.',
    'delicate abstract proportions expressing {}.',
    'bold abstract dimensions that convey {}.',
    'subtle abstract relationships representing {}.',
    
    # Light and shadow in abstraction
    'abstract light effects expressing {}.',
    'shadows in abstract art evoking {}.',
    'luminous abstractions that convey {}.',
    'dark abstract elements representing {}.',
    'bright abstract passages embodying {}.',
    'contrast between light and dark suggesting {}.',
    'glowing abstract forms evoking {}.',
    'shadowy abstractions expressing {}.',
    'radiant abstract compositions that convey {}.',
    'subdued abstract lighting representing {}.',
    
    # Spatial relationships in abstract art
    'abstract spatial relationships expressing {}.',
    'depth in abstract art evoking {}.',
    'flat abstract compositions that convey {}.',
    'layered abstract spaces representing {}.',
    'compressed abstract depth embodying {}.',
    'expansive abstract space suggesting {}.',
    'crowded abstract elements evoking {}.',
    'sparse abstract arrangements expressing {}.',
    'dense abstract compositions that convey {}.',
    'open abstract fields representing {}.',
    
    # Medium and technique specific templates
    'oil painting abstractions that evoke {}.',
    'watercolor abstractions expressing {}.',
    'acrylic abstract works conveying {}.',
    'mixed media abstractions representing {}.',
    'digital abstract art embodying {}.',
    'collage elements in abstraction suggesting {}.',
    'painted abstract surfaces evoking {}.',
    'drawn abstract elements expressing {}.',
    'printmaking abstractions that convey {}.',
    'sculptural abstractions representing {}.',
    
    # Artistic style and movement templates
    'expressionist abstractions that evoke {}.',
    'minimalist abstract art expressing {}.',
    'gestural abstractions conveying {}.',
    'geometric abstractions representing {}.',
    'lyrical abstract works embodying {}.',
    'hard-edge abstractions suggesting {}.',
    'action painting elements evoking {}.',
    'color field paintings expressing {}.',
    'contemporary abstractions that convey {}.',
    'modern abstract works representing {}.',
    
    # Emotional intensity and complexity templates
    'subtle abstract expressions of {}.',
    'intense abstract manifestations of {}.',
    'complex abstract emotions including {}.',
    'simple abstract representations of {}.',
    'overwhelming abstract expressions of {}.',
    'gentle abstract suggestions of {}.',
    'powerful abstract statements of {}.',
    'delicate abstract hints of {}.',
    'bold abstract declarations of {}.',
    'nuanced abstract expressions of {}.',
    
    # Conceptual and philosophical templates
    'abstract concepts visualizing {}.',
    'non-verbal abstract communication of {}.',
    'pure abstract emotion of {}.',
    'distilled abstract essence of {}.',
    'concentrated abstract feeling of {}.',
    'abstract meditation on {}.',
    'visual abstract poetry of {}.',
    'abstract philosophical expression of {}.',
    'transcendent abstract representation of {}.',
    'universal abstract language of {}.',
    
    # Viewer response and interpretation templates
    'abstractions that make viewers feel {}.',
    'abstract art that inspires {}.',
    'visual abstractions that trigger {}.',
    'abstract works that generate {}.',
    'paintings that abstractly communicate {}.',
    'art that non-representationally expresses {}.',
    'abstractions that universally convey {}.',
    'visual languages of abstract {}.',
    'non-literal artistic expressions of {}.',
    'abstract artistic interpretations of {}.'
    ]
}


"""
EmoSet数据集专用模板配置
基于LaFTer模型的标准模板格式设计
"""

# EmoSet数据集的情感模板配置
EMOSET_TEMPLATES = [
    # 基础情感描述模板
    'a photo of {}.',
    'a picture showing {}.',
    'an image expressing {}.',
    'a scene of {}.',
    'a photo that evokes {}.',
    'an image that conveys {}.',
    'a picture that depicts {}.',
    'a visual representation of {}.',
    
    # 面部表情相关模板
    'a photo of a person showing {}.',
    'a picture of someone feeling {}.',
    'an image of a person experiencing {}.',
    'a photo of people displaying {}.',
    'a picture of a human expression of {}.',
    'an image of facial {} emotion.',
    'a photo capturing the emotion of {}.',
    'a picture revealing {} feelings.',
    
    # 场景和情境相关模板
    'a photo of a {} scene.',
    'a picture of a {} moment.',
    'an image of a {} situation.',
    'a scene that evokes {}.',
    'a moment filled with {}.',
    'a situation expressing {}.',
    'an environment of {}.',
    'a setting that conveys {}.',
    
    # 社交媒体风格模板
    'a social media photo showing {}.',
    'a snapshot of {}.',
    'a candid photo capturing {}.',
    'a social photo expressing {}.',
    'an Instagram-style image of {}.',
    'a shared moment of {}.',
    'a posted photo showing {}.',
    
    # 艺术风格模板
    'an artistic image of {}.',
    'a creative photo expressing {}.',
    'art that evokes {}.',
    'an artistic representation of {}.',
    'a visual artwork conveying {}.',
    'a creative expression of {}.',
    'an aesthetic image of {}.',
    
    # 视觉属性相关模板（基于EmoSet的属性注释）
    'a bright photo of {}.',
    'a colorful image of {}.',
    'a vibrant picture of {}.',
    'a vivid scene of {}.',
    'a well-lit photo of {}.',
    'a dynamic image of {}.',
    'an expressive picture of {}.',
    
    # 动作相关模板
    'a photo of someone in {}.',
    'a picture of a person during {}.',
    'an image of human {} behavior.',
    'a photo capturing {} actions.',
    'a scene of {} activity.',
    'a moment of {} expression.',
    
    # 情感强度相关模板
    'a photo showing intense {}.',
    'a picture of strong {}.',
    'an image of deep {}.',
    'a scene of overwhelming {}.',
    'a moment of pure {}.',
    'a powerful expression of {}.',
    
    # 对比和比较模板
    'a photo unlike {} emotion.',
    'an image contrasting with {}.',
    'a picture opposite to {}.',
    'a scene devoid of {}.',
    
    # 时间和持续性模板
    'a photo during a moment of {}.',
    'a picture at the peak of {}.',
    'an image in the midst of {}.',
    'a scene before {} sets in.',
    'a moment when {} emerges.',
    
    # 集体和个人模板
    'a photo of individual {}.',
    'a picture of shared {}.',
    'an image of collective {}.',
    'a scene of group {}.',
    'a moment of personal {}.',
    'a photo of communal {}.',
]

# 针对特定情感的专门模板
EMOTION_SPECIFIC_TEMPLATES = {
    'a photo of {} and laughter.',
    'a picture of {} and joy.',
    'an image of {} and entertainment.',
    'a scene of {} and fun.',
    'a moment of {} and delight.',
    'a photo of playful {}.',
    'a picture of cheerful {}.',
    'an image of lighthearted {}.',
    'a scene of humorous {}.',
    'a photo of someone laughing with {}.',
    'a picture of joyful {}.',
    'an image of entertaining {}.',

    'a photo of {} and rage.',
    'a picture of {} and fury.',
    'an image of {} and hostility.',
    'a scene of {} and aggression.',
    'a moment of {} and frustration.',
    'a photo of intense {}.',
    'a picture of fierce {}.',
    'an image of violent {}.',
    'a scene of heated {}.',
    'a photo of explosive {}.',
    'a picture of burning {}.',
    'an image of seething {}.',

    'a photo of {} and wonder.',
    'a picture of {} and amazement.',
    'an image of {} and reverence.',
    'a scene of {} and inspiration.',
    'a moment of {} and admiration.',
    'a photo of breathtaking {}.',
    'a picture of magnificent {}.',
    'an image of spectacular {}.',
    'a scene of sublime {}.',
    'a photo of majestic {}.',
    'a picture of overwhelming {}.',
    'an image of transcendent {}.',

    'a photo of {} and peace.',
    'a picture of {} and satisfaction.',
    'an image of {} and tranquility.',
    'a scene of {} and serenity.',
    'a moment of {} and calm.',
    'a photo of peaceful {}.',
    'a picture of serene {}.',
    'an image of relaxed {}.',
    'a scene of comfortable {}.',
    'a photo of gentle {}.',
    'a picture of soothing {}.',
    'an image of harmonious {}.',

    'a photo of {} and revulsion.',
    'a picture of {} and repulsion.',
    'an image of {} and aversion.',
    'a scene of {} and loathing.',
    'a moment of {} and distaste.',
    'a photo of repulsive {}.',
    'a picture of revolting {}.',
    'an image of nauseating {}.',
    'a scene of sickening {}.',
    'a photo of disturbing {}.',
    'a picture of offensive {}.',

    'a photo of {} and enthusiasm.',
    'a picture of {} and energy.',
    'an image of {} and thrill.',
    'a scene of {} and exhilaration.',
    'a moment of {} and vitality.',
    'a photo of dynamic {}.',
    'a picture of vibrant {}.',
    'an image of energetic {}.',
    'a scene of thrilling {}.',
    'a photo of electrifying {}.',
    'a picture of invigorating {}.',
    'an image of stimulating {}.',

    'a photo of {} and terror.',
    'a picture of {} and dread.',
    'an image of {} and anxiety.',
    'a scene of {} and panic.',
    'a moment of {} and horror.',
    'a photo of frightening {}.',
    'a picture of scary {}.',
    'an image of terrifying {}.',
    'a scene of menacing {}.',
    'a photo of ominous {}.',
    'a picture of threatening {}.',
    'an image of sinister {}.',

    'a photo of {} and sorrow.',
    'a picture of {} and grief.',
    'an image of {} and melancholy.',
    'a scene of {} and depression.',
    'a moment of {} and despair.',
    'a photo of sorrowful {}.',
    'a picture of mournful {}.',
    'an image of melancholic {}.',
    'a scene of tragic {}.',
    'a photo of heartbreaking {}.',
    'a picture of poignant {}.',
    'an image of touching {}.',
    
}

# 基于EmoSet属性的模板
ATTRIBUTE_BASED_TEMPLATES = {

    'a bright photo of {}.',
    'a dark image of {}.',
    'a well-lit picture of {}.',
    'a shadowy scene of {}.',
    'a luminous photo of {}.',
    'a dim image of {}.',
    'a radiant picture of {}.',
    'a gloomy scene of {}.',

    'a colorful photo of {}.',
    'a vibrant image of {}.',
    'a vivid picture of {}.',
    'a muted scene of {}.',
    'a saturated photo of {}.',
    'a monochrome image of {}.',
    'a rainbow-like picture of {}.',
    'a grayscale scene of {}.',

    'a photo of {} in nature.',
    'a picture of {} indoors.',
    'an image of {} outdoors.',
    'a scene of {} in urban setting.',
    'a photo of {} in public space.',
    'a picture of {} at home.',
    'an image of {} in workplace.',
    'a scene of {} in social gathering.',


    'a photo of someone while feeling {}.',
    'a picture of a person  with {}.',
    'an image of human  expressing {}.',
    'a scene of  action showing {}.',
    'a photo of  activity with {}.',
    'a picture of  behavior and {}.',

}


"""
EmoSet数据集综合模板配置 - 包含所有类型的模板
总模板数量: 500+ 个
"""

# 综合大模板集合 - 整合所有模板类型
COMPREHENSIVE_EMOSET_TEMPLATES = [
    # ==================== 基础情感描述模板 ====================
    'a photo of {}.',
    'a picture showing {}.',
    'an image expressing {}.',
    'a scene of {}.',
    'a photo that evokes {}.',
    'an image that conveys {}.',
    'a picture that depicts {}.',
    'a visual representation of {}.',
    'a snapshot capturing {}.',
    'a moment of {}.',
    'a display of {}.',
    'an exhibition of {}.',
    'a manifestation of {}.',
    'a demonstration of {}.',
    'an illustration of {}.',
    'a portrayal of {}.',
    'a depiction of {}.',
    'a reflection of {}.',
    
    # ==================== 面部表情相关模板 ====================
    'a photo of a person showing {}.',
    'a picture of someone feeling {}.',
    'an image of a person experiencing {}.',
    'a photo of people displaying {}.',
    'a picture of a human expression of {}.',
    'an image of facial {} emotion.',
    'a photo capturing the emotion of {}.',
    'a picture revealing {} feelings.',
    'a portrait of {} emotion.',
    'a close-up of {} expression.',
    'a face showing {}.',
    'an expression of {}.',
    'a countenance of {}.',
    'a visage displaying {}.',
    'facial features expressing {}.',
    'a human face conveying {}.',
    
    # ==================== 场景和情境相关模板 ====================
    'a photo of a {} scene.',
    'a picture of a {} moment.',
    'an image of a {} situation.',
    'a scene that evokes {}.',
    'a moment filled with {}.',
    'a situation expressing {}.',
    'an environment of {}.',
    'a setting that conveys {}.',
    'a backdrop of {}.',
    'a context of {}.',
    'an atmosphere of {}.',
    'a mood of {}.',
    'an ambiance of {}.',
    'a surrounding of {}.',
    'a circumstance of {}.',
    'a scenario of {}.',
    'an occurrence of {}.',
    'an instance of {}.',
    
    # ==================== 社交媒体风格模板 ====================
    'a social media photo showing {}.',
    'a snapshot of {}.',
    'a candid photo capturing {}.',
    'a social photo expressing {}.',
    'an Instagram-style image of {}.',
    'a shared moment of {}.',
    'a posted photo showing {}.',
    'a viral image of {}.',
    'a trending photo of {}.',
    'a selfie showing {}.',
    'a story photo of {}.',
    'a feed image expressing {}.',
    'a social share of {}.',
    'a public post of {}.',
    'a community photo of {}.',
    'a networked image of {}.',
    
    # ==================== 艺术风格模板 ====================
    'an artistic image of {}.',
    'a creative photo expressing {}.',
    'art that evokes {}.',
    'an artistic representation of {}.',
    'a visual artwork conveying {}.',
    'a creative expression of {}.',
    'an aesthetic image of {}.',
    'a stylized photo of {}.',
    'an expressive artwork of {}.',
    'a masterpiece of {}.',
    'a composition showing {}.',
    'a fine art piece of {}.',
    'a gallery image of {}.',
    'an exhibition photo of {}.',
    'a curated image of {}.',
    'a designed photo of {}.',
    'an illustrated moment of {}.',
    'a crafted image of {}.',
    
    # ==================== 视觉属性相关模板 ====================
    'a bright photo of {}.',
    'a colorful image of {}.',
    'a vibrant picture of {}.',
    'a vivid scene of {}.',
    'a well-lit photo of {}.',
    'a dynamic image of {}.',
    'an expressive picture of {}.',
    'a dark image of {}.',
    'a shadowy scene of {}.',
    'a luminous photo of {}.',
    'a dim image of {}.',
    'a radiant picture of {}.',
    'a gloomy scene of {}.',
    'a muted scene of {}.',
    'a saturated photo of {}.',
    'a monochrome image of {}.',
    'a rainbow-like picture of {}.',
    'a grayscale scene of {}.',
    'a high-contrast image of {}.',
    'a low-contrast photo of {}.',
    'a sharp picture of {}.',
    'a blurred image of {}.',
    'a focused photo of {}.',
    'a soft picture of {}.',
    'a harsh image of {}.',
    'a gentle photo of {}.',
    
    # ==================== 动作相关模板 ====================
    'a photo of someone in {}.',
    'a picture of a person during {}.',
    'an image of human {} behavior.',
    'a photo capturing {} actions.',
    'a scene of {} activity.',
    'a moment of {} expression.',
    'an action shot of {}.',
    'a motion picture of {}.',
    'a movement showing {}.',
    'a gesture of {}.',
    'a pose expressing {}.',
    'a stance of {}.',
    'a position showing {}.',
    'a posture of {}.',
    'a behavior indicating {}.',
    'an activity of {}.',
    
    # ==================== 情感强度相关模板 ====================
    'a photo showing intense {}.',
    'a picture of strong {}.',
    'an image of deep {}.',
    'a scene of overwhelming {}.',
    'a moment of pure {}.',
    'a powerful expression of {}.',
    'an extreme display of {}.',
    'a profound moment of {}.',
    'a concentrated dose of {}.',
    'a heightened state of {}.',
    'an amplified emotion of {}.',
    'a magnified feeling of {}.',
    'an exaggerated expression of {}.',
    'a dramatic display of {}.',
    'a theatrical moment of {}.',
    'a cinematic scene of {}.',
    'a compelling image of {}.',
    'a striking photo of {}.',
    'a remarkable picture of {}.',
    'an extraordinary scene of {}.',
    
    # ==================== 对比和比较模板 ====================
    'a photo unlike {} emotion.',
    'an image contrasting with {}.',
    'a picture opposite to {}.',
    'a scene devoid of {}.',
    'a photo lacking {}.',
    'an image without {}.',
    'a picture missing {}.',
    'a scene free from {}.',
    'a photo beyond {}.',
    'an image transcending {}.',
    'a picture surpassing {}.',
    'a scene exceeding {}.',
    
    # ==================== 时间和持续性模板 ====================
    'a photo during a moment of {}.',
    'a picture at the peak of {}.',
    'an image in the midst of {}.',
    'a scene before {} sets in.',
    'a moment when {} emerges.',
    'a photo at the height of {}.',
    'a picture during the climax of {}.',
    'an image in the process of {}.',
    'a scene while {} unfolds.',
    'a moment as {} develops.',
    'a photo when {} begins.',
    'a picture as {} concludes.',
    'an image throughout {}.',
    'a scene spanning {}.',
    'a moment encompassing {}.',
    'a photo covering {}.',
    
    # ==================== 集体和个人模板 ====================
    'a photo of individual {}.',
    'a picture of shared {}.',
    'an image of collective {}.',
    'a scene of group {}.',
    'a moment of personal {}.',
    'a photo of communal {}.',
    'a picture of private {}.',
    'an image of public {}.',
    'a scene of social {}.',
    'a moment of intimate {}.',
    'a photo of universal {}.',
    'a picture of common {}.',
    'an image of mutual {}.',
    'a scene of joint {}.',
    'a moment of unified {}.',
    'a photo of synchronized {}.',
    
    # ==================== 环境和场所模板 ====================
    'a photo of {} in nature.',
    'a picture of {} indoors.',
    'an image of {} outdoors.',
    'a scene of {} in urban setting.',
    'a photo of {} in public space.',
    'a picture of {} at home.',
    'an image of {} in workplace.',
    'a scene of {} in social gathering.',
    'a photo of {} in natural environment.',
    'a picture of {} in artificial setting.',
    'an image of {} in familiar place.',
    'a scene of {} in strange location.',
    'a photo of {} in crowded area.',
    'a picture of {} in empty space.',
    'an image of {} in noisy environment.',
    'a scene of {} in quiet place.',
    'a photo of {} in bright location.',
    'a picture of {} in dark setting.',
    'an image of {} in warm place.',
    'a scene of {} in cool environment.',
    
    # ==================== 技术和风格模板 ====================
    'a professional photo of {}.',
    'an amateur picture of {}.',
    'a documentary image of {}.',
    'a journalistic photo of {}.',
    'a commercial picture of {}.',
    'an editorial image of {}.',
    'a fashion photo of {}.',
    'a lifestyle picture of {}.',
    'a portrait showing {}.',
    'a landscape with {}.',
    'a still life of {}.',
    'a street photo of {}.',
    'a travel image of {}.',
    'a nature picture of {}.',
    'an urban photo of {}.',
    'a rural image of {}.',
    'a contemporary picture of {}.',
    'a vintage photo of {}.',
    'a modern image of {}.',
    'a classic picture of {}.',
    'a retro photo of {}.',
    'a futuristic image of {}.',
    
    # ==================== 感官和体验模板 ====================
    'a photo that makes you feel {}.',
    'a picture that induces {}.',
    'an image that triggers {}.',
    'a scene that provokes {}.',
    'a moment that inspires {}.',
    'a photo that generates {}.',
    'a picture that creates {}.',
    'an image that produces {}.',
    'a scene that stimulates {}.',
    'a moment that awakens {}.',
    'a photo that arouses {}.',
    'a picture that evokes {}.',
    'an image that summons {}.',
    'a scene that calls forth {}.',
    'a moment that brings out {}.',
    'a photo that draws out {}.',
    
    # ==================== 文化和社会模板 ====================
    'a cultural expression of {}.',
    'a social display of {}.',
    'a traditional moment of {}.',
    'a modern scene of {}.',
    'a contemporary image of {}.',
    'a historical photo of {}.',
    'a universal picture of {}.',
    'a global scene of {}.',
    'a local moment of {}.',
    'a regional photo of {}.',
    'a cultural representation of {}.',
    'a societal reflection of {}.',
    'a community expression of {}.',
    'a family moment of {}.',
    'a generational photo of {}.',
    'an age-specific picture of {}.',
    
    # ==================== 抽象和概念模板 ====================
    'a symbolic representation of {}.',
    'a metaphorical image of {}.',
    'an allegorical picture of {}.',
    'a conceptual photo of {}.',
    'an abstract expression of {}.',
    'a philosophical moment of {}.',
    'a psychological scene of {}.',
    'a spiritual image of {}.',
    'a mental picture of {}.',
    'an emotional landscape of {}.',
    'a symbolic photo of {}.',
    'a representative image of {}.',
    'an emblematic picture of {}.',
    'a characteristic scene of {}.',
    'a typical moment of {}.',
    'a quintessential photo of {}.',
    
    # ==================== 组合和复合模板 ====================
    'a bright and colorful photo of {}.',
    'a dark and moody image of {}.',
    'a vibrant and dynamic picture of {}.',
    'a soft and gentle scene of {}.',
    'a sharp and intense moment of {}.',
    'a warm and inviting photo of {}.',
    'a cool and distant image of {}.',
    'a loud and overwhelming picture of {}.',
    'a quiet and subtle scene of {}.',
    'a complex and layered moment of {}.',
    'a simple and pure photo of {}.',
    'a rich and detailed image of {}.',
    'a sparse and minimal picture of {}.',
    'a crowded and busy scene of {}.',
    'a spacious and open moment of {}.',
    'a intimate and personal photo of {}.',
    'a public and shared image of {}.',
    'a hidden and secret picture of {}.',
    'a obvious and clear scene of {}.',
    'a mysterious and enigmatic moment of {}.',
]

# 特殊组合模板 - 情感 + 属性组合
EMOTION_ATTRIBUTE_COMBINATIONS = [
    # 亮度 + 情感组合
    'a bright photo filled with {}.',
    'a luminous image radiating {}.',
    'a well-lit scene of {}.',
    'a radiant picture of {}.',
    'a glowing photo of {}.',
    'a brilliant image of {}.',
    'a shining picture of {}.',
    'a gleaming scene of {}.',
    'a sparkling photo of {}.',
    'a dazzling image of {}.',
    
    'a dark photo shrouded in {}.',
    'a shadowy image of {}.',
    'a dim scene of {}.',
    'a gloomy picture of {}.',
    'a murky photo of {}.',
    'a somber image of {}.',
    'a dusky picture of {}.',
    'a twilight scene of {}.',
    'a moonlit photo of {}.',
    'a nocturnal image of {}.',
    
    # 色彩 + 情感组合
    'a colorful explosion of {}.',
    'a vibrant display of {}.',
    'a vivid portrayal of {}.',
    'a saturated scene of {}.',
    'a chromatic photo of {}.',
    'a polychromatic image of {}.',
    'a multicolored picture of {}.',
    'a rainbow scene of {}.',
    'a prismatic photo of {}.',
    'a kaleidoscopic image of {}.',
    
    'a monochrome study of {}.',
    'a grayscale image of {}.',
    'a black and white photo of {}.',
    'a sepia-toned picture of {}.',
    'a muted scene of {}.',
    'a desaturated image of {}.',
    'a neutral-toned photo of {}.',
    'a subdued picture of {}.',
    'a restrained scene of {}.',
    'a understated image of {}.',
    
    # 动作 + 情感组合
    'a photo of dynamic {} in motion.',
    'an image of active {} behavior.',
    'a picture of energetic {} expression.',
    'a scene of lively {} activity.',
    'a moment of animated {} display.',
    'a photo of spirited {} demonstration.',
    'an image of vigorous {} action.',
    'a picture of intense {} movement.',
    'a scene of passionate {} gesture.',
    'a moment of fervent {} expression.',
    
    'a photo of still {} contemplation.',
    'an image of calm {} reflection.',
    'a picture of peaceful {} meditation.',
    'a scene of quiet {} observation.',
    'a moment of serene {} presence.',
    'a photo of tranquil {} being.',
    'an image of restful {} state.',
    'a picture of composed {} demeanor.',
    'a scene of balanced {} existence.',
    'a moment of centered {} awareness.',
    
    # 环境 + 情感组合
    'a natural photo of organic {}.',
    'an outdoor image of fresh {}.',
    'a wilderness picture of wild {}.',
    'a forest scene of untamed {}.',
    'a mountain photo of elevated {}.',
    'an ocean image of vast {}.',
    'a sky picture of limitless {}.',
    'a field scene of open {}.',
    'a garden photo of cultivated {}.',
    'a park image of maintained {}.',
    
    'an indoor photo of contained {}.',
    'a room image of intimate {}.',
    'a house picture of domestic {}.',
    'an office scene of professional {}.',
    'a studio photo of controlled {}.',
    'a gallery image of curated {}.',
    'a theater picture of performed {}.',
    'a restaurant scene of social {}.',
    'a library photo of quiet {}.',
    'a hospital image of healing {}.',
    
    # 时间 + 情感组合
    'a morning photo of awakening {}.',
    'a dawn image of emerging {}.',
    'a sunrise picture of hopeful {}.',
    'a noon scene of peak {}.',
    'an afternoon photo of warm {}.',
    'a sunset image of golden {}.',
    'a twilight picture of fading {}.',
    'an evening scene of settling {}.',
    'a night photo of mysterious {}.',
    'a midnight image of deep {}.',
    
    # 季节 + 情感组合
    'a spring photo of blooming {}.',
    'a summer image of vibrant {}.',
    'an autumn picture of changing {}.',
    'a winter scene of quiet {}.',
    'a seasonal photo of timely {}.',
    'a cyclical image of recurring {}.',
    'a temporal picture of fleeting {}.',
    'a momentary scene of brief {}.',
    'an eternal photo of lasting {}.',
    'a timeless image of enduring {}.',
]
